[project]
name = "learn-pandas"
version = "0.1.0"
description = "Learn Pandas Code"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.30.1",
    "numpy>=2.3.2",
    "pandas>=2.3.1",
]
